### ISSUE TITLE
Последний маленький шаг

### ISSUE THREAD

**Issue by kate-fsd** [Sprashivaite/slider#19]
![Peek 2021-06-15 17-24](https://user-images.githubusercontent.com/66846004/122070466-aba47080-cdfe-11eb-87df-efd0d8413c70.gif)

Проверь поведение при таких параметрах

**Comment by Sprashivaite** [comment]
В целом, это сделано намеренно, так как значение кратное шагу кажется более логично. Хотя визуально кажется лучше, чтобы он прижимался к max значению.

**Comment by kate-fsd** [comment]
> В целом, это сделано намеренно, так как значение кратное шагу кажется более логично. Хотя визуально думаю лучше, чтобы он прижимался к max значению.

Такое требование есть в риззоме. Чтобы оставался последнии шаг, даже если он меньше остальных

**Comment by kate-fsd** [comment]
![Peek 2021-06-21 23-12](https://user-images.githubusercontent.com/66846004/122822031-3d701a00-d2e6-11eb-8233-f921e2387a71.gif)

**Comment by kate-fsd** [comment]
Комбо)

**Comment by Geksanit** [comment]
Мне кажется последний шаг странным. Я бы его убрал, не позволил бы вводить в инпуты не подходящие значения, у них как раз есть атрибут "step". А раз уж сделали так, то ладно :)
