### ISSUE TITLE
Код

### ISSUE THREAD

**Issue by kate-fsd** [Sprashivaite/slider#35]
subscribe(eventTypes.elementsRendered, model.notifyListeners.bind(model))
К тому моменту когда view начал рендериться в модели должны лежать валидные значения. Соответственно оповестить подписчиков модель должна в тот момент когда провалидировала и установила значения

**Comment by kate-fsd** [comment]
if (point === 'firstPoint') {
      this.model.moveToValue({ value: result, ...this.view.getFirstPointData()});
    }
    
    1. Слово move не вяжется с моделью
    2. Неправильно то что для обновления модели требуется взять что то из вью. У тебя в модели вроде все нужные данные уже есть?

**Comment by kate-fsd** [comment]
firstTooltip!: ViewTooltip;

  secondTooltip!: ViewTooltip;
  
ненужный код

**Comment by kate-fsd** [comment]
if (point === 'firstPoint') {
      this.model.moveToValue({ value: result, ...this.view.getFirstPointData()});
    }
    
    1. Слово move не вяжется с моделью
    2. Неправильно то что для обновления модели требуется взять что то из вью. У тебя в модели вроде все нужные данные уже есть?

**Comment by kate-fsd** [comment]
getElements(): viewElements { 
    let secondPoint
    if(this.secondPoint) secondPoint = this.secondPoint.divElement
    return {
      slider: this.slider.divElement,
      field: this.field.divElement,
      firstPoint: this.firstPoint.divElement,
      secondPoint,
    }
  }

можно просто secondPoint: this.secondPoint.divElement. Проверка выше ничего не дает

**Comment by Sprashivaite** [comment]
> ```
>   getElements(): viewElements { 
>     let secondPoint
>     if(this.secondPoint) secondPoint = this.secondPoint.divElement
>     return {
>       slider: this.slider.divElement,
>       field: this.field.divElement,
>       firstPoint: this.firstPoint.divElement,
>       secondPoint,
>     }
>   }
> ```
> 
> можно просто secondPoint: this.secondPoint.divElement. Проверка выше ничего не дает

Иначе ошибка вылетает

**Comment by kate-fsd** [comment]
Тут больше дело вкуса, это просто совет. Когда в коде совсем нет вертикальных отступов он плохо читается. Лучше разбивать на небольшие блоки по смыслу, особенно если код сложный
![image](https://user-images.githubusercontent.com/66846004/124518284-b4c9a180-ddee-11eb-93c4-68f0a1e7c96e.png)

**Comment by kate-fsd** [comment]
Обычно в папке utils / helpers лежат помощники, которые слабо связаны с конкретным классом. У тебя все эти функции должны быть методами класса

**Comment by kate-fsd** [comment]
в SliderPlugin сделано правильно

**Comment by kate-fsd** [comment]
> Иначе ошибка вылетает

можно secondPoint: this.secondPoint?.divElement
можно и как есть оставить

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/124598848-bedeb500-de6d-11eb-8b8b-49a39d48b4e4.png)

лучше убрать .data('sliderPlugin')  и сделать так чтобы  метод .sliderPlugin сразу возвращал что нужно
